stages:
  - build
  - deploy

variables:
  APP_IMAGE: registry.gitlab.com/gastove/cookbook/application
  APP_VERSION: 0.1.0
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  NAMESPACE: cookbook
  KUBECTL_URL: https://storage.googleapis.com/kubernetes-release/release/v1.13.3/bin/linux/amd64/kubectl

build:
  services:
    - docker:dind
  image: docker:stable
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $APP_IMAGE:latest || true
    - >
        docker build
        --cache-from $APP_IMAGE:latest
        --tag $APP_IMAGE:$APP_VERSION
        --tag $APP_IMAGE:$CI_COMMIT_SHA
        --tag $APP_IMAGE:latest
        --file build/Dockerfile .
  except:
    - master

build_and_push:
  services:
    - docker:dind
  image: docker:stable
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $APP_IMAGE:latest || true
    - >
        docker build
        --cache-from $APP_IMAGE:latest
        --tag $APP_IMAGE:$APP_VERSION
        --tag $APP_IMAGE:$CI_COMMIT_SHA
        --tag $APP_IMAGE:latest
        --file build/Dockerfile .
    - docker push $APP_IMAGE:$CI_COMMIT_SHA
    - docker push $APP_IMAGE:$APP_VERSION
    - docker push $APP_IMAGE:latest
  only:
    - master

deploy:
  stage: deploy
  image: alpine
  environment: production
  script:
    - apk add --no-cache curl
    - curl -LO $KUBECTL_URL
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - mkdir ~/.kube
    - echo "$KUBECONFIG" > ~/.kube/config
    - cat ~/.kube/config
    # We deploy in three steps so we can update the image tag use in the deployment
    - kubectl -n "$NAMESPACE" apply -f deploy/service.yaml
    - kubectl -n "$NAMESPACE" apply -f deploy/namespace.yaml
    - cat deploy/deployment.yaml | sed s/REPLACE/"$CI_COMMIT_SHA"/ | kubectl -n "$NAMESPACE" apply -f -
  only:
    - master
