image: docker:stable

services:
  - docker:dind

variables:
  BUILD_CONTAINER_IMAGE: registry.gitlab.com/gastove/cookbook/builder
  APP_IMAGE: registry.gitlab.com/gastove/cookbook/application
  APP_VERSION: 0.1.0
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker pull $BUILD_CONTAINER_IMAGE:latest
    - >
        docker build --cache-from $BUILD_CONTAINER_IMAGE:latest
        --tag $BUILD_CONTAINER_IMAGE:$CI_COMMIT_SHA
        --tag $BUILD_CONTAINER_IMAGE:latest
        --file build/Dockerfile.Build .
    - docker push $BUILD_CONTAINER_IMAGE:$CI_COMMIT_SHA
    - docker push $BUILD_CONTAINER_IMAGE:latest
    - >
        docker build
        --tag $APP_IMAGE:$APP_VERSION
        --tag $APP_IMAGE:$CI_COMMIT_SHA
        --file build/Dockerfile.App .
    - docker push $APP_IMAGE:$CI_COMMIT_SHA
    - docker push $APP_IMAGE:$APP_VERSION

