apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: cookbook-webapp
  name: cookbook-webapp
  selfLink: /apis/extensions/v1beta1/namespaces/cookbook/deployments/cookbook-webapp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: cookbook-webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cookbook-webapp
    spec:
      containers:
        - name: cookbook-webapp
          image: registry.gitlab.com/gastove/cookbook/application:REPLACE
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 5000
              protocol: TCP
            - name: metrics
              containerPort: 5005
              protocol: TCP

          resources: {}

          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

          env:
            - name: DBX_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dbx-credentials
                  key: dbx-access-token

            - name: BLOG_DIR
              value: "/blog/html"

            # This is the default value if unset, but -- it's also what we want,
            # so let's be explicit.
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

            - name: ASPNETCORE_URLS
              value: http://+:5000

          livenessProbe:
            httpGet:
              path: /healthz
              port: http-port
            initialDelaySeconds: 10
            periodSeconds: 300
            timeoutSeconds: 3

          readinessProbe:
            httpGet:
              path: /healthz
              port: http-port
            initialDelaySeconds: 10
            periodSeconds: 300
            timeoutSeconds: 3

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
