apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: cookbook-webapp
  name: cookbook-webapp
  selfLink: /apis/extensions/v1beta1/namespaces/cookbook/deployments/cookbook-webapp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: cookbook-webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cookbook-webapp
    spec:
      containers:
        - name: cookbook-webapp
          image: registry.gitlab.com/gastove/cookbook/application:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP

          resources: {}

          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

          env:
            - name: DBX_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dbx-credentials
                  key: dbx-access-token

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
