apiVersion: v1
kind: Service
metadata:
  labels:
    run: cookbook-webapp
  name: cookbook-webapp

spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080

  selector:
    run: cookbook-webapp
  type: NodePort
