---
apiVersion: v1
kind: Service
metadata:
  name: cookbook-webapp
  labels:
    run: cookbook-webapp
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"cookbook-cdn-backend"}}'

spec:
  selector:
    run: cookbook-webapp

  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 5000

  type: NodePort
